# Generated by Django 4.0.4 on 2022-11-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, unique=True)),
                ('sid', models.IntegerField(max_length=10)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=10)),
                ('dept', models.CharField(choices=[('Electrical Engineering', 'EE'), ('Industrial Engineering', 'IE'), ('Civil Engineering', 'CE'), ('Chemical Engineering', 'ChE'), ('Mechanical Engineering', 'ME'), ('Computer Engineering', 'CN')], max_length=50)),
            ],
        ),
    ]
