# Generated by Django 4.0.4 on 2022-11-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
