# Generated by Django 4.0.4 on 2022-11-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_student_sid_alter_student_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(max_length=10),
        ),
    ]
